### PR TITLE
Make everything translatable

### PR DESCRIPTION
**Pull request by NathanBnm**
With this PR your app can now be translated :smile:

### CODE REVIEW

**Comment by NathanBnm** [comment]
> I only have one question, is the potfile generated or will the msgids need to be updated to match the strings in the source code as the strings are changed in the source?

No, when adding or updating strings you have to run the following commands in the build directory:
```
ninja com.github.chasinglogic.tardis-update-po
ninja extra-update-po
```
This will automatically regenerate the appropriate `.pot` file for main and metadata translations, and generate or update the language files associated to the language codes in the `LINGUAS` file.

Let me know if you have any other questions

**Comment by NathanBnm** [comment]
Note: I'll resolve conflicts ASAP

**Comment by chasinglogic** [comment]
Thanks!, once the conflicts are sorted I will merge this and release v1.1.0 for the appcenter

**Comment by NathanBnm** [comment]
@chasinglogic conflicts are resolved. But it seems that there is an error in the `appdata.xml` file, that's why the build is failing.

**Comment by chasinglogic** [comment]
I will merge this and sort out the problem after the fact. Thanks again for all your help!

**Pull request merged**
